version: '3'

services:
  jmeter-db:
    image: postgres
    environment:
    - POSTGRES_DB=jmeter
    - POSTGRES_PASSWORD=jmeter
    - POSTGRES_USER=jmeter
    - PGDATA=/database
    ports:
      - 5432:5432